### PR TITLE
Converted to superclass shorthand.

### PR DESCRIPTION
**Pull request by decadentsavant**
Utilized ({super.key}) syntax

### CODE REVIEW

**Comment by RobertBrunhage** [comment]
It looks good, have you made sure to test it locally, reviewing on the phone is always a bit hard haha.

Also consider bumping the minor version and add the change to the CHANGELOG

**Review by RobertBrunhage — CHANGES_REQUESTED** [review]
See comment above

**Comment by RobertBrunhage** [comment]
Haha no worries, have a nice vacation!

**Comment by decadentsavant** [comment]
During testing, I was glancing at the Riverpod docs (still learning Dart/Flutter & Riverpod!) and see that StateNotifierProvider uses `TodosNotifier(): super([]);` in the example.

What is the common use case here? Is the most common use case for the developer to use `super.xParameter` or do they initialize unique code blocks as in the example?

I'm unsure if converting to the new syntax is net positive in this snippet. Suggestion?

**Comment by decadentsavant** [comment]
@RobertBrunhage ...see question above.

**Comment by RobertBrunhage** [comment]
@decadentsavant `super` is just a shorthand to do it.

you can do this if you want to be able to pass the state
```dart
class SomethingStateNotifier extends StateNotifier<int> {
  SomethingStateNotifier(
    super._state,
  ); 
}
```

And if you want a default value, you can just make it optional
```dart
class SomethingStateNotifier extends StateNotifier<int> {
  SomethingStateNotifier(
    [super._state = 1]
  ); 
}
```

But haven't worked on riverpod for a bit so @pythonhubpy, maybe you know if this is a good change or not?

We could also keep the normal use of `super` in this case and only use it for things we are sure as such as the `key` for widgets.

**Comment by decadentsavant** [comment]
Shall we leave it as is? Pull, then wait for feedback?

**Comment by RobertBrunhage** [comment]
@decadentsavant if you update the version as explained here: https://github.com/RobertBrunhage/flutter-riverpod-snippets/pull/25#issuecomment-1210636947

And remove the changes to the `StateNotifier` regarding `super` we can merge!

**Comment by pythonhubdev** [comment]
@RobertBrunhage can this be merged it's been open for a long time.

**Review by RobertBrunhage — APPROVED** [review]

**Comment by RobertBrunhage** [comment]
Fixes #24

**Pull request merged**
