### PR TITLE
Added support for all providers, freezed and json_serializable

### PR DESCRIPTION
**Pull request by pythonhubpy**
- Added support for all types of riverpod providers separately
- Added support for `freezed` package and `json serializable`

### CODE REVIEW

**Comment by RobertBrunhage** [comment]
Looks good, could you remove the `freezed` and `json serializable` ones as this is strictly for riverpod?

**Comment by pythonhubpy** [comment]
Sure will remove that

**Comment by pythonhubpy** [comment]
I have removed `freezed` and `json_serializable` also updated the readme

**Comment by RobertBrunhage** [comment]
> I have removed `freezed` and `json_serializable` also updated the readme

Great, looks good!

**Pull request merged**
