### PR TITLE
This adds support for creating the ConsumerWidget with ScopedReader watch as part of build

### PR DESCRIPTION
**Pull request by bettdouglas**

### CODE REVIEW

**Comment by Merrit** [comment]
This is excellent, just what I needed. I added it to my personal snippets, but I hope it gets merged! ❤️

**Comment by RobertBrunhage** [comment]
Awesome, didn't notice this, thanks @bettdouglas!

This will be built and pushed directly so make sure to increment the version number in `package.json` to `0.1.2` as well as adding it to the `readme.md` file!

**Review by RobertBrunhage — CHANGES_REQUESTED** [review]
Awesome, didn't notice this, thanks @bettdouglas!

This will be built and pushed directly so make sure to increment the version number in package.json to 0.1.2 as well as adding it to the readme.md file!

here is an example, when I did it https://github.com/RobertBrunhage/flutter-riverpod-snippets/commit/218819c40cb3b924c71ed93ec6c401884766a80e

**Comment by RobertBrunhage** [comment]
Also keep in mind that `riverpod` 1.0 is coming soon which may change the syntax a small bit: https://github.com/rrousselGit/river_pod/issues/335

**Comment by RobertBrunhage** [comment]
Closed in favor of #6

**Pull request closed without merging**
