### PR TITLE
update comsumer to match the latest version of riverpod

### PR DESCRIPTION
**Pull request by tbm98**

### CODE REVIEW

**Comment by tbm98** [comment]
Hi @RobertBrunhage.
Can you review it and release a new version for this change?

**Review by RobertBrunhage — APPROVED** [review]
@tbm98 thanks for the contribution!

**Comment by RobertBrunhage** [comment]
@tbm98 new version has just been published as `1.0.2`, it will probably be live in a couple of minutes to an hour 😊

**Comment by tbm98** [comment]
@RobertBrunhage Thank you 😋

**Pull request merged**
